baseURL = 'https://oggcamp.github.io/'
languageCode = 'en-gb'
title = 'OggCamp 2026'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.
# Load Theme Module
[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
# Main Menu (navbar)
[menu]
[[menu.main]]
  # The page reference (pageRef) is useful for menu highlighting
  # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
  pageRef="/"
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  pageRef="about"
  name = 'About'
  url = '/about/'
  weight = 30
[[menu.main]]
  pageRef="posts"
  name = 'Posts'
  url = '/posts/'
  weight = 20
[[menu.main]]
  pageRef="history"
  name = 'History'
  url = '/history/'
  weight = 30
[[menu.main]]
  pageRef="sponsors"
  name = 'Sponsors'
  url = '/Sponsors/'
  weight = 30
[[menu.main]]
  pageRef="guidelines"
  name = 'Talk Guidelines'
  url = '/guidelines/'
  weight = 30
[[menu.main]]
  pageRef="code-of-conduct"
  name = 'Code of Conduct'
  url = '/code-of-conduct/'
  weight = 30
[[menu.main]]
  pageRef="venue"
  name = 'Venue'
  url = '/venue/'
  weight = 30
[[menu.main]]
  pageRef="tickets"
  name = 'Tickets'
  url = 'https://tickets.oggcamp.org/'
  weight = 30

# Global Site Parameters
[params]
  sitename = "OggCamp 2026"
  defaultColor = "auto" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Minimal Hugo blog theme with light and dark mode support"
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  tocOpen = false # set to true to open table of contents by default
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatenated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).
  dateFormat = "" # date format used to show dates on various pages. If nothing is specified, then "2 Jan 2006" format is used.
  # See https://gohugo.io/functions/time/format/ for available date formats.
  rssFeedDescription = "summary" # available options: 1) summary 2) full
  # summary - includes a short summary of the blog post in the RSS feed. Generated using Hugo .Summary .
  # full - includes full blog post in the RSS feed. Generated using Hugo .Content .
  # By default (or if nothing is specified), summary is used.

# Author Parameters (Defines detail on homepage)
[params.author]
  avatar = "oggcamp-2024-logo-150px.png"
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "OggCamp 2026"
  name = "OggCamp"
  description = "OggCamp is an unconference celebrating Free Culture, Free and Open Source Software, hardware hacking, digital rights, and all manner of collaborative cultural activities and is committed to creating a conference that is as inclusive as possible. If you’ve got a story to tell, no matter your background or current status, whether it’s your first talk or you’ve loads of experience, as long as the talk is connected (somehow) to our theme then we want to know about it. Curious what happens at an OggCamp? Check the about page, or look at our social links below."

# Allow to override webmanifest options
[params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

# Social Media Icons
[[params.socialIcons]]
  name = "github"
    url = "https://github.com/oggcamp"
[[params.socialIcons]]
  name = "mastodon"
    url = "https://mastodon.social/@oggcamp@mastodon.social"
[[params.socialIcons]]
  name = "bluesky"
    url = "https://bsky.app/profile/oggcamp.bsky.social"
[[params.socialIcons]]
  name = "x"
    url = "https://twitter.com/oggcamp"
[[params.socialIcons]]
  name = "telegram"
    url = "https://t.me/joinchat/AAAAAAsF-xo4ol9jAjNW8A"
[[params.socialIcons]]
  name = "matrix"
    url = "https://matrix.to/#/#oggcamp:matrix.org"
[[params.socialIcons]]
  name = "discord"
    url = "https://discord.gg/4DcDk6Y"
[[params.socialIcons]]
  name = "irc"
    url = "irc://irc.libera.chat/oggcamp"

# Cache location required for GH Pages (https://gohugo.io/host-and-deploy/host-on-github-pages/)
[caches]
  [caches.images]
    dir = ':cacheDir/images'